### ISSUE TITLE
Roadmap to 0.1

### ISSUE THREAD

**Issue by gajomi** [gajomi/OrderStatistics.jl#5]
The main goal of 0.1 is to fill out all the basic generic functionality for IID sequences. This issue keeps track of the list of items needed for this.
1. [ ] Define type and basic constructor methods
   - [x] `ScalarOrderStatistic`
   - [x] `JointOrderStatistic`
   - [ ] `Range`
   - [ ] `Spacing`
   - [ ] `JointSpacing`
2. [ ] Implement "standard" `Distribution' method for univariate types (rand,pdf,cdf,mean)
   - [x] `ScalarOrderStatistic`
   - [x] `JointOrderStatistic`
   - [ ] `Range`
   - [ ] `Spacing`
   - [ ] `JointSpacing`
3.  [ ] Pretty printing for all types

Of course, what is considered "basic" and "generic" is rather subjective, so use this issue for questions about the scope of 0.1.
